sonar.projectName=lakehouse/presto
sonar.branch.name=master
sonar.exclusions=presto-native-execution/**,**/tests/**,presto-extracted/**
sonar.projectKey=412037-1346077
sonar.scm.disabled=true
sonar.java.binaries=presto-extracted
