apiVersion: v1
kind: Pod
metadata:
    namespace: jenkins-agent
    labels:
        containers: maven
spec:
    serviceAccountName: jenkins-agent
    containers:
    - name: maven
      image: 299095523242.dkr.ecr.us-east-1.amazonaws.com/ahanaio/devops/agent-prestodb:20220412Ha8188f4
      resources:
        requests:
          memory: "4Gi"
          cpu: "1000m"
        limits:
          memory: "8Gi"
          cpu: "2000m"
      tty: true
      command:
      - cat
