apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins-agent
  labels:
    containers: dind
spec:
  serviceAccountName: jenkins-agent
  containers:
  - name: dind
    image: docker:20.10.16-dind-alpine3.15
    tty: true
    resources:
      requests:
        memory: "16Gi"
        cpu: "4000m"
      limits:
        memory: "16Gi"
        cpu: "4000m"
    securityContext:
      privileged: true
