name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 0.291)'
        required: true
      publish_as_latest:
        description: 'Also publish as latest version'
        type: boolean
        default: true
        required: false

env:
  VERSION: ${{ github.event.inputs.version }}
  DOCKER_REPO: unidevel/test


jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.VERSION }}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Maven build
        run: mvn clean install -DskipTests

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: presto-artifacts-${{ env.VERSION }}
          retention-days: 1
          path: |
            presto-server/target/presto-server-*.tar.gz
            presto-cli/target/presto-cli-*-executable.jar

  docker-build:
    needs: [maven-build]
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.VERSION }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: presto-artifacts-${{ env.VERSION }}
          path: ./

      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0

      - name: Create and use builder
        run: |
          docker buildx create --name container --use
          docker buildx inspect --bootstrap

      - name: Move artifacts to docker directory
        run: |
          mv ./presto-server/target/presto-server-*.tar.gz docker/
          mv ./presto-cli/target/presto-cli-*-executable.jar docker/

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: docker
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          file: docker/Dockerfile
          push: false
          build-args: |
            PRESTO_VERSION=${{ env.VERSION }}
            JMX_PROMETHEUS_JAVAAGENT_VERSION=0.20.0
          outputs: type=docker,dest=/tmp/presto-image.tar
          tags: ${{ env.DOCKER_REPO }}:${{ env.VERSION }}

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/presto-image.tar
          retention-days: 1

  dockerhub-publish:
    needs: [docker-build]
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: ./

      - name: Load Docker image
        run: docker load --input presto-image.tar

      - name: Tag and push to DockerHub
        run: |
          docker push ${{ env.DOCKER_REPO }}:${{ env.VERSION }}
          if [[ "${{ github.event.inputs.publish_as_latest }}" == "true" ]]; then
            docker tag ${{ env.DOCKER_REPO }}:${{ env.VERSION }} ${{ env.DOCKER_REPO }}:latest
            docker push ${{ env.DOCKER_REPO }}:latest
          fi
          tags: |
            ${{ env.DOCKER_REPO }}:${{ env.VERSION }}
            ${{ github.event.inputs.publish_as_latest == 'true' && format('{0}:latest', env.DOCKER_REPO) || '' }}

  github-publish:
    needs: [docker-build]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      packages: write
      contents: read
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: ./

      - name: Load Docker image
        run: docker load --input image.tar

      - name: Tag and push to GitHub Packages
        run: |
          docker tag ${{ env.DOCKER_REPO }}:${{ env.VERSION }} ghcr.io/${{ github.repository_owner }}/presto:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/presto:${{ env.VERSION }}
          if [[ "${{ github.event.inputs.publish_as_latest }}" == "true" ]]; then
            docker tag ${{ env.DOCKER_REPO }}:${{ env.VERSION }} ghcr.io/${{ github.repository_owner }}/presto:latest
            docker push ghcr.io/${{ github.repository_owner }}/presto:latest
          fi
