name: Publish Prestissimo Image

on:
  workflow_dispatch:
    inputs:
      branch_or_tag:
        description: 'Branch or tag to checkout (e.g., master, 0.295)'
        required: true
        default: 'master'
      dependency_image:
        description: 'Dependency image to use'
        required: true
        default: 'prestodb/presto-native-dependency:centos-latest'
      os:
        description: 'Operating system (ubuntu/centos)'
        required: true
        default: 'centos'
        type: choice
        options:
          - centos
          - ubuntu
      tag_suffix:
        description: 'Tag suffix (can be empty)'
        required: false
        default: ''
      tag_latest:
        description: 'Tag the image as latest'
        type: boolean
        default: true
        required: false

concurrency:
  group: publish-prestissimo-image
  cancel-in-progress: false

env:
  JAVA_VERSION: ${{ vars.JAVA_VERSION || '17' }}
  JAVA_DISTRIBUTION: ${{ vars.JAVA_DISTRIBUTION || 'temurin' }}
  DOCKER_REPO: ${{ github.repository }}
  ORG_NAME: ${{ github.repository_owner }}
  IMAGE_NAME: prestissimo
  GIT_CI_USER: ${{ vars.GIT_CI_USER || 'prestodb-ci' }}
  GIT_CI_EMAIL: ${{ vars.GIT_CI_EMAIL || 'ci@lists.prestodb.io' }}

jobs:
  publish-prestissimo-image:
    strategy:
      matrix:
        arch: [amd64, arm64]
      fail-fast: false
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    environment: release
    timeout-minutes: 150
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up JDK ${{ env.JAVA_DISTRIBUTION }}/${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_or_tag }}
          fetch-depth: 1

      - name: Configure git
        run: |
          git config --global user.email "${{ env.GIT_CI_EMAIL }}"
          git config --global user.name "${{ env.GIT_CI_USER }}"

          echo "Currently on: $(git rev-parse --abbrev-ref HEAD)"
          echo "Commit SHA: $(git rev-parse HEAD)"
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Checkout submodules
        working-directory: presto-native-execution
        run: |
          df -h
          make submodules

      - name: Extract version
        run: |
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Raw version: $VERSION"

          if [ -z "$VERSION" ]; then
            echo "Failed to extract project version with Maven"
            exit 1
          fi

          if [[ "$VERSION" == *"-SNAPSHOT" ]]; then
            # Remove -SNAPSHOT and append commit SHA
            CLEAN_VERSION=${VERSION%-SNAPSHOT}
            TAG_VERSION="${CLEAN_VERSION}-${COMMIT_SHA}"
            echo "SNAPSHOT version detected, using: $TAG_VERSION"
          else
            TAG_VERSION="$VERSION"
            echo "Release version detected, using: $TAG_VERSION"
          fi

          echo "VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.0.0

      - name: Set up buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.0.0

      - name: Set up builder
        run: |
          docker buildx create --name container --use
          docker buildx inspect --bootstrap

      - name: Set image tag and base image
        run: |
          TAG_BASE="${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:${{ inputs.os }}-${{ env.VERSION }}-${{ matrix.arch }}"

          if [[ -n "${{ inputs.tag_suffix }}" ]]; then
            echo "IMAGE_TAG=${TAG_BASE}-${{ inputs.tag_suffix }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${TAG_BASE}" >> $GITHUB_ENV
          fi

          if [[ "${{ inputs.os }}" == "ubuntu" ]]; then
            echo "BASE_IMAGE=ubuntu:22.04" >> $GITHUB_ENV
          else
            echo "BASE_IMAGE=quay.io/centos/centos:stream9" >> $GITHUB_ENV
          fi

      - name: Build prestissimo image
        working-directory: presto-native-execution
        run: |
          df -h
          echo "Using image tag: $IMAGE_TAG"
          echo "Using dependency image: ${{ inputs.dependency_image }}"
          echo "Using base image: $BASE_IMAGE"

          if [[ "${{ matrix.arch }}" == "arm64" ]]; then
            BUILD_ARGS="--build-arg ARM_BUILD_TARGET=generic"
          else
            BUILD_ARGS=""
          fi

          # Build the prestissimo image using Docker buildx
          docker buildx build \
            --platform linux/${{ matrix.arch }} \
            --build-arg DEPENDENCY_IMAGE=${{ inputs.dependency_image }} \
            --build-arg BASE_IMAGE=$BASE_IMAGE \
            --build-arg OSNAME=${{ inputs.os }} \
            --build-arg BUILD_TYPE=Release \
            ${BUILD_ARGS} \
            -f scripts/dockerfiles/prestissimo-runtime.dockerfile \
            -t ${{ env.IMAGE_TAG }} \
            --load \
            .

      - name: Publish image
        run: |
          set -e
          docker push ${{ env.IMAGE_TAG }}

          if [[ "${{ inputs.tag_latest }}" == "true" ]]; then
            LATEST_TAG="${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:${{ inputs.os }}-${{ matrix.arch }}-latest"
            docker tag ${{ env.IMAGE_TAG }} ${LATEST_TAG}
            docker push ${LATEST_TAG}
            echo "Tagged and pushed as latest: ${LATEST_TAG}"
          fi

  create-manifest:
    needs: publish-prestissimo-image
    runs-on: ubuntu-latest
    environment: release
    permissions:
      packages: write
      contents: read
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_or_tag }}
          fetch-depth: 1

      - name: Extract version
        run: |
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Raw version: $VERSION"

          if [ -z "$VERSION" ]; then
            echo "Failed to extract project version with Maven"
            exit 1
          fi

          if [[ "$VERSION" == *"-SNAPSHOT" ]]; then
            # Remove -SNAPSHOT and append commit SHA
            CLEAN_VERSION=${VERSION%-SNAPSHOT}
            COMMIT_SHA=$(git rev-parse --short HEAD)
            TAG_VERSION="${CLEAN_VERSION}-${COMMIT_SHA}"
            echo "SNAPSHOT version detected, using: $TAG_VERSION"
          else
            TAG_VERSION="$VERSION"
            echo "Release version detected, using: $TAG_VERSION"
          fi

          echo "VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Create and push multi-arch manifest
        run: |
          ORG_NAME="${{ github.repository_owner }}"
          IMAGE_NAME="prestissimo"
          OS="${{ inputs.os }}"
          VERSION="${{ env.VERSION }}"
          
          # Determine tag suffix
          if [[ -n "${{ inputs.tag_suffix }}" ]]; then
            TAG_SUFFIX="-${{ inputs.tag_suffix }}"
          else
            TAG_SUFFIX=""
          fi
          
          # Create manifest for the versioned tag
          MANIFEST_TAG="${ORG_NAME}/${IMAGE_NAME}:${OS}-${VERSION}${TAG_SUFFIX}"
          AMD64_TAG="${ORG_NAME}/${IMAGE_NAME}:${OS}-${VERSION}-amd64${TAG_SUFFIX}"
          ARM64_TAG="${ORG_NAME}/${IMAGE_NAME}:${OS}-${VERSION}-arm64${TAG_SUFFIX}"
          
          echo "Creating manifest: ${MANIFEST_TAG}"
          docker manifest create ${MANIFEST_TAG} ${AMD64_TAG} ${ARM64_TAG}
          docker manifest push ${MANIFEST_TAG}
          
          # Create latest manifest if requested
          if [[ "${{ inputs.tag_latest }}" == "true" ]]; then
            LATEST_MANIFEST="${ORG_NAME}/${IMAGE_NAME}:${OS}-latest"
            LATEST_AMD64="${ORG_NAME}/${IMAGE_NAME}:${OS}-amd64-latest"
            LATEST_ARM64="${ORG_NAME}/${IMAGE_NAME}:${OS}-arm64-latest"
            
            echo "Creating latest manifest: ${LATEST_MANIFEST}"
            docker manifest create ${LATEST_MANIFEST} ${LATEST_AMD64} ${LATEST_ARM64}
            docker manifest push ${LATEST_MANIFEST}
          fi

# Made with Bob
